package dashboard;

/*
 * This class has been automatically generated by the webMethods Developer(TM).
 *
 */

import java.io.*;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Vector;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import com.wm.util.Table;
import com.wm.data.*;
import com.wm.util.coder.IDataCodable;
import com.wm.app.b2b.util.GenUtil;
import com.wm.app.b2b.client.Context;
import com.wm.app.b2b.client.ServiceException;

public class SQL{
	static String user = "a0184930";
	static String pw = "Spektor33!";
    public static void main(String[] args)
    {
    	System.setProperty("webdriver.chrome.driver", "C://schema_creation/chromedriver.exe");
    	WebDriver driver = new ChromeDriver();
    	driver.get("https://pconor:Spektor33!@l4dwipap054/WmRoot/log-server-recent.dsp");
//    	WebElement ele = driver.findElement(By.xpath("//*[contains(.,'06:32:37')]"));
//    	System.out.println(ele.getText());
    	//System.out.println(driver.getPageSource());
    	String longstr = driver.getPageSource().toString();
    	String[] line = longstr.split("\n");

    	for (int i=0;i<line.length;i++){
    		if(line[i].contains("06:32:37")&&line[i].contains("Successfully inserted in messageQ table")){
    			String newone = line[i].substring(line[i].indexOf("----")-5, line[i].indexOf("----"));
    			System.out.println(newone);
    		}
    	}
    }
}

